[package]
name = "clock-sysvar-program"
version = "4.1.0-alpha.0"
edition = "2021"

[dependencies]
solana-account-info = "3.1.1"
solana-program = "4.1.0"
solana-program-entrypoint = "3.1.1"
solana-program-error = "3.0.1"
solana-pubkey = "4.3.0"
solana-sysvar = "4.3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
